Fix the EmailVerified column value from '1' to true (#2843)
EmailVerified column type is bool.
but these queries were a string type and a number type.
this is ok in Mysql but cause errors in Postgresql.

like this(user_test.go:970).

```
[2016/05/02 23:20:47 KST] [EROR] /api/v3/users/reset_password:SqlUserStore.UpdatePassword code=500 rid=ezj4agkewibjzni3ptybq5knbh uid=9z53qbkxj7nq9m8r8jbb47enzr ip=::1 We couldn't update the user password [details: id=8bymugax77yhfff9zj4frthapc, pq: column "emailverified" is of type boolean but expression is of type integer]
--- FAIL: TestResetPassword (0.90s)
user_test.go:970: : We couldn't update the user password, id=8bymugax77yhfff9zj4frthapc, pq: column "emailverified" is of type boolean but expression is of type integer
```